export const jobs = [
  {
    id: 1,
    jobTitle: "Human Resources Manager",
    location: "Indonesia",
    careerArea: "n/a",
  },
  {
    id: 2,
    jobTitle: "Nurse Practicioner",
    location: "Sweden",
    careerArea: "Savings Institutions",
  },
  {
    id: 3,
    jobTitle: "Environmental Specialist",
    location: "Indonesia",
    careerArea: "Oil & Gas Production",
  },
  {
    id: 4,
    jobTitle: "VP Marketing",
    location: "New Caledonia",
    careerArea: "Biotechnology: Biological Products (No Diagnostic Substances)",
  },
  {
    id: 5,
    jobTitle: "Editor",
    location: "Honduras",
    careerArea: "n/a",
  },
  {
    id: 6,
    jobTitle: "Human Resources Assistant III",
    location: "Indonesia",
    careerArea: "Industrial Machinery/Components",
  },
  {
    id: 7,
    jobTitle: "Research Associate",
    location: "Bulgaria",
    careerArea: "Electric Utilities: Central",
  },
  {
    id: 8,
    jobTitle: "Paralegal",
    location: "Thailand",
    careerArea: "Catalog/Specialty Distribution",
  },
  {
    id: 9,
    jobTitle: "Research Nurse",
    location: "Philippines",
    careerArea: "n/a",
  },
  {
    id: 10,
    jobTitle: "GIS Technical Architect",
    location: "China",
    careerArea: "Medical/Dental Instruments",
  },
  {
    id: 11,
    jobTitle: "Office Assistant II",
    location: "Azerbaijan",
    careerArea: "Major Banks",
  },
  {
    id: 12,
    jobTitle: "Desktop Support Technician",
    location: "Japan",
    careerArea: "Industrial Specialties",
  },
  {
    id: 13,
    jobTitle: "Assistant Manager",
    location: "Japan",
    careerArea: "Business Services",
  },
  {
    id: 14,
    jobTitle: "Software Consultant",
    location: "Indonesia",
    careerArea: "Biotechnology: Biological Products (No Diagnostic Substances)",
  },
  {
    id: 15,
    jobTitle: "VP Sales",
    location: "France",
    careerArea: "n/a",
  },
  {
    id: 16,
    jobTitle: "Geologist III",
    location: "Philippines",
    careerArea: "Computer Software: Prepackaged Software",
  },
  {
    id: 17,
    jobTitle: "Safety Technician I",
    location: "Indonesia",
    careerArea: "n/a",
  },
  {
    id: 18,
    jobTitle: "Software Test Engineer IV",
    location: "Belarus",
    careerArea: "EDP Services",
  },
  {
    id: 19,
    jobTitle: "Programmer II",
    location: "Armenia",
    careerArea: "Television Services",
  },
  {
    id: 20,
    jobTitle: "Environmental Tech",
    location: "France",
    careerArea: "Industrial Specialties",
  },
  {
    id: 21,
    jobTitle: "Occupational Therapist",
    location: "China",
    careerArea: "Electronic Components",
  },
  {
    id: 22,
    jobTitle: "Quality Control Specialist",
    location: "Ukraine",
    careerArea: "Food Distributors",
  },
  {
    id: 23,
    jobTitle: "Structural Analysis Engineer",
    location: "Indonesia",
    careerArea: "Oil & Gas Production",
  },
  {
    id: 24,
    jobTitle: "VP Product Management",
    location: "Peru",
    careerArea: "n/a",
  },
  {
    id: 25,
    jobTitle: "Research Associate",
    location: "Portugal",
    careerArea: "Electric Utilities: Central",
  },
  {
    id: 26,
    jobTitle: "Nurse",
    location: "France",
    careerArea: "Beverages (Production/Distribution)",
  },
  {
    id: 27,
    jobTitle: "Biostatistician II",
    location: "China",
    careerArea: "Major Pharmaceuticals",
  },
  {
    id: 28,
    jobTitle: "Software Consultant",
    location: "Ecuador",
    careerArea: "Real Estate Investment Trusts",
  },
  {
    id: 29,
    jobTitle: "Financial Analyst",
    location: "Tajikistan",
    careerArea: "Telecommunications Equipment",
  },
  {
    id: 30,
    jobTitle: "Senior Financial Analyst",
    location: "Madagascar",
    careerArea: "Automotive Aftermarket",
  },
  {
    id: 31,
    jobTitle: "Librarian",
    location: "Indonesia",
    careerArea: "Advertising",
  },
  {
    id: 32,
    jobTitle: "Librarian",
    location: "France",
    careerArea: "Marine Transportation",
  },
  {
    id: 33,
    jobTitle: "Clinical Specialist",
    location: "China",
    careerArea: "Real Estate",
  },
  {
    id: 34,
    jobTitle: "Paralegal",
    location: "Peru",
    careerArea: "Major Pharmaceuticals",
  },
  {
    id: 35,
    jobTitle: "Programmer IV",
    location: "Indonesia",
    careerArea: "Computer Software: Prepackaged Software",
  },
  {
    id: 36,
    jobTitle: "Chemical Engineer",
    location: "Peru",
    careerArea: "Medical/Dental Instruments",
  },
  {
    id: 37,
    jobTitle: "Legal Assistant",
    location: "Poland",
    careerArea: "Real Estate Investment Trusts",
  },
  {
    id: 38,
    jobTitle: "Nuclear Power Engineer",
    location: "China",
    careerArea: "Major Banks",
  },
  {
    id: 39,
    jobTitle: "Developer III",
    location: "Indonesia",
    careerArea: "n/a",
  },
  {
    id: 40,
    jobTitle: "VP Quality Control",
    location: "Sudan",
    careerArea: "Major Pharmaceuticals",
  },
  {
    id: 41,
    jobTitle: "Occupational Therapist",
    location: "Brazil",
    careerArea: "Telecommunications Equipment",
  },
  {
    id: 42,
    jobTitle: "Director of Sales",
    location: "Thailand",
    careerArea: "Beverages (Production/Distribution)",
  },
  {
    id: 43,
    jobTitle: "Registered Nurse",
    location: "Sweden",
    careerArea: "Finance: Consumer Services",
  },
  {
    id: 44,
    jobTitle: "Speech Pathologist",
    location: "Peru",
    careerArea: "Aerospace",
  },
  {
    id: 45,
    jobTitle: "Graphic Designer",
    location: "Brazil",
    careerArea: "n/a",
  },
  {
    id: 46,
    jobTitle: "Professor",
    location: "Philippines",
    careerArea: "Construction/Ag Equipment/Trucks",
  },
  {
    id: 47,
    jobTitle: "Administrative Officer",
    location: "Ukraine",
    careerArea: "Business Services",
  },
  {
    id: 48,
    jobTitle: "Director of Sales",
    location: "Ukraine",
    careerArea: "Metal Fabrications",
  },
  {
    id: 49,
    jobTitle: "Geological Engineer",
    location: "Japan",
    careerArea: "Computer Software: Programming, Data Processing",
  },
  {
    id: 50,
    jobTitle: "Food Chemist",
    location: "France",
    careerArea: "Oil & Gas Production",
  },
  {
    id: 51,
    jobTitle: "Desktop Support Technician",
    location: "Portugal",
    careerArea: "Investment Bankers/Brokers/Service",
  },
  {
    id: 52,
    jobTitle: "VP Quality Control",
    location: "Palestinian Territory",
    careerArea: "Packaged Foods",
  },
  {
    id: 53,
    jobTitle: "Account Coordinator",
    location: "Philippines",
    careerArea: "n/a",
  },
  {
    id: 54,
    jobTitle: "Mechanical Systems Engineer",
    location: "Canada",
    careerArea: "Investment Managers",
  },
  {
    id: 55,
    jobTitle: "Senior Quality Engineer",
    location: "China",
    careerArea: "n/a",
  },
  {
    id: 56,
    jobTitle: "Marketing Assistant",
    location: "Peru",
    careerArea: "Business Services",
  },
  {
    id: 57,
    jobTitle: "Dental Hygienist",
    location: "Colombia",
    careerArea: "Oil & Gas Production",
  },
  {
    id: 58,
    jobTitle: "Occupational Therapist",
    location: "South Korea",
    careerArea: "Metal Fabrications",
  },
  {
    id: 59,
    jobTitle: "Payment Adjustment Coordinator",
    location: "Russia",
    careerArea: "Life Insurance",
  },
  {
    id: 60,
    jobTitle: "Geological Engineer",
    location: "Indonesia",
    careerArea: "Investment Bankers/Brokers/Service",
  },
  {
    id: 61,
    jobTitle: "Help Desk Operator",
    location: "Canada",
    careerArea: "Finance/Investors Services",
  },
  {
    id: 62,
    jobTitle: "Speech Pathologist",
    location: "Indonesia",
    careerArea: "Diversified Commercial Services",
  },
  {
    id: 63,
    jobTitle: "Administrative Assistant III",
    location: "Guatemala",
    careerArea: "Investment Bankers/Brokers/Service",
  },
  {
    id: 64,
    jobTitle: "Internal Auditor",
    location: "Brazil",
    careerArea: "Specialty Foods",
  },
  {
    id: 65,
    jobTitle: "Editor",
    location: "United States",
    careerArea: "Biotechnology: Laboratory Analytical Instruments",
  },
  {
    id: 66,
    jobTitle: "GIS Technical Architect",
    location: "France",
    careerArea: "Industrial Machinery/Components",
  },
  {
    id: 67,
    jobTitle: "Speech Pathologist",
    location: "Luxembourg",
    careerArea: "Biotechnology: Biological Products (No Diagnostic Substances)",
  },
  {
    id: 68,
    jobTitle: "Assistant Professor",
    location: "Greece",
    careerArea: "n/a",
  },
  {
    id: 69,
    jobTitle: "Legal Assistant",
    location: "Portugal",
    careerArea: "Electrical Products",
  },
  {
    id: 70,
    jobTitle: "Statistician I",
    location: "Liberia",
    careerArea: "Restaurants",
  },
  {
    id: 71,
    jobTitle: "Compensation Analyst",
    location: "France",
    careerArea: "Advertising",
  },
  {
    id: 72,
    jobTitle: "Programmer Analyst IV",
    location: "Philippines",
    careerArea: "n/a",
  },
  {
    id: 73,
    jobTitle: "Human Resources Assistant II",
    location: "United States",
    careerArea: "Consumer Electronics/Appliances",
  },
  {
    id: 74,
    jobTitle: "Biostatistician IV",
    location: "Philippines",
    careerArea: "Industrial Machinery/Components",
  },
  {
    id: 75,
    jobTitle: "Biostatistician I",
    location: "Indonesia",
    careerArea: "Business Services",
  },
  {
    id: 76,
    jobTitle: "Automation Specialist III",
    location: "China",
    careerArea: "Major Banks",
  },
  {
    id: 77,
    jobTitle: "Civil Engineer",
    location: "Czech Republic",
    careerArea: "n/a",
  },
  {
    id: 78,
    jobTitle: "Nurse",
    location: "Iran",
    careerArea: "Finance/Investors Services",
  },
  {
    id: 79,
    jobTitle: "Accountant II",
    location: "Spain",
    careerArea: "Major Banks",
  },
  {
    id: 80,
    jobTitle: "Design Engineer",
    location: "Ireland",
    careerArea: "Business Services",
  },
  {
    id: 81,
    jobTitle: "Health Coach II",
    location: "China",
    careerArea: "Computer Software: Prepackaged Software",
  },
  {
    id: 82,
    jobTitle: "Nuclear Power Engineer",
    location: "Albania",
    careerArea: "Marine Transportation",
  },
  {
    id: 83,
    jobTitle: "Environmental Specialist",
    location: "China",
    careerArea: "Business Services",
  },
  {
    id: 84,
    jobTitle: "VP Quality Control",
    location: "China",
    careerArea: "Major Banks",
  },
  {
    id: 85,
    jobTitle: "Senior Developer",
    location: "Cameroon",
    careerArea: "Finance: Consumer Services",
  },
  {
    id: 86,
    jobTitle: "Civil Engineer",
    location: "China",
    careerArea: "Auto Parts:O.E.M.",
  },
  {
    id: 87,
    jobTitle: "Operator",
    location: "China",
    careerArea: "Major Banks",
  },
  {
    id: 88,
    jobTitle: "Senior Financial Analyst",
    location: "Indonesia",
    careerArea: "Hospital/Nursing Management",
  },
  {
    id: 89,
    jobTitle: "Structural Analysis Engineer",
    location: "Slovenia",
    careerArea: "Precious Metals",
  },
  {
    id: 90,
    jobTitle: "Chief Design Engineer",
    location: "Brazil",
    careerArea: "Railroads",
  },
  {
    id: 91,
    jobTitle: "Engineer II",
    location: "Philippines",
    careerArea: "Investment Managers",
  },
  {
    id: 92,
    jobTitle: "Accountant IV",
    location: "Philippines",
    careerArea: "Homebuilding",
  },
  {
    id: 93,
    jobTitle: "Legal Assistant",
    location: "Indonesia",
    careerArea: "n/a",
  },
  {
    id: 94,
    jobTitle: "Research Assistant I",
    location: "China",
    careerArea: "Medical/Dental Instruments",
  },
  {
    id: 95,
    jobTitle: "Mechanical Systems Engineer",
    location: "United States",
    careerArea: "Major Banks",
  },
  {
    id: 96,
    jobTitle: "Senior Cost Accountant",
    location: "China",
    careerArea: "Oil/Gas Transmission",
  },
  {
    id: 97,
    jobTitle: "Web Developer IV",
    location: "Botswana",
    careerArea: "Investment Managers",
  },
  {
    id: 98,
    jobTitle: "Developer II",
    location: "Portugal",
    careerArea: "Beverages (Production/Distribution)",
  },
  {
    id: 99,
    jobTitle: "Senior Cost Accountant",
    location: "Indonesia",
    careerArea: "Business Services",
  },
  {
    id: 100,
    jobTitle: "Data Coordiator",
    location: "Cyprus",
    careerArea: "n/a",
  },
];
